action_dim: 7
action_model_type: DiT-B
data_root_dir: /aifs4su/mmcode/worldm/open_x_embodiment/fractal20220817_data/2tasks
future_action_window_size: 15
hf_token: .hf_token
image_aug: true
is_resume: false
load_all_data_for_training: true
past_action_window_size: 0
pretrained_checkpoint: /aifs4su/mmcode/worldm/RoboCrafter/save_checkpoints/ww_training_512_v1.0_rt1/checkpoints/epoch=37-step=80000.ckpt
repeated_diffusion_steps: 8
resume_epoch: null
resume_step: null
run_id: 2tasks_${date +%Y%m%d_%H%M%S}--image_aug
run_id_note: null
run_root_dir: /aifs4su/mmcode/worldm/videoact/VgmACT
save_interval: 10000
seed: 42
trackers:
- jsonl
- wandb
use_ema: false
vla:
  base_vlm: prism-dinosiglip-224px+7b
  data_mix: fractal20220817_data
  enable_gradient_checkpointing: true
  enable_mixed_precision_training: true
  epochs: 100
  expected_world_size: 2
  freeze_llm_backbone: false
  freeze_vision_backbone: false
  global_batch_size: 2
  learning_rate: 2.0e-05
  lr_scheduler_type: constant
  max_grad_norm: 1.0
  max_steps: null
  per_device_batch_size: 1
  reduce_in_full_precision: true
  shuffle_buffer_size: 250000
  train_strategy: fsdp-full-shard
  type: prism-dinosiglip-224px+oxe+diffusion
  unfreeze_last_llm_layer: false
  vla_id: prism-dinosiglip-224px+oxe+diffusion
  warmup_ratio: 0.0
  weight_decay: 0.0
wandb_entity: litwellchi
wandb_project: CogACT-rt1-pretrain-2tasks
